updated main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -103,13 +103,22 @@ jobs:
           push: true
           tags: katarina74/taski_gateway:latest
 
-    deploy:
+  deploy:
     runs-on: ubuntu-latest
     needs: 
       - build_and_push_to_docker_hub
     steps:
       - name: Checkout repo
         uses: actions/checkout@v3
+      
+      - name: Check if docker-compose.production.yml exists
+        run: |
+          if [ ! -f "docker-compose.production.yml" ]; then
+            echo "ERROR: docker-compose.production.yml not found!"
+            ls -la
+            exit 1
+          fi
+        shell: bash
       
       - name: Create .env file from secrets
         run: |
@@ -122,7 +131,6 @@ jobs:
           DB_PORT=${{ secrets.DB_PORT }}
           SECRET_KEY=${{ secrets.SECRET_KEY }}
           DEBUG=${{ secrets.DEBUG }}
-          # Добавьте другие переменные по необходимости
           EOF
       
       # Копируем docker-compose.production.yml на продакшен-сервер
